// import kavling
import Kavling1 from "./assets/img/KEYONGAN/kavling keyongan.jpg";
import Denah from "./assets/img/KEYONGAN/DENAH KEYONGAN.png";
import Kavling2 from "./assets/img/NGINGAS/kavling ngingas.jpg";
import Denah2 from "./assets/img/NGINGAS/DENAH NGINGAS.png";

//dealdone
import gambar1 from "./assets/img/dealdone/deal1.jpg";
import gambar2 from "./assets/img/dealdone/deal2.jpg";
import gambar3 from "./assets/img/dealdone/deal3.jpg";
import gambar4 from "./assets/img/dealdone/deal4.jpg";
import gambar5 from "./assets/img/dealdone/deal5.jpg";
import gambar6 from "./assets/img/dealdone/deal6.jpg";
import gambar7 from "./assets/img/dealdone/deal7.jpg";

//testi
import person1 from "./assets/img/testimoni/person1.png";

export const housesData = [
  {
    id: 1,
    type: "A3",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "70",
    denah: Denah,
  },
  {
    id: 2,
    type: "B2",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "52",
    denah: Denah,
  },
  {
    id: 3,
    type: "B3",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "59",
    denah: Denah,
  },
  {
    id: 4,
    type: "B4",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "59",
    denah: Denah,
  },
  {
    id: 5,
    type: "B5",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "60",
    denah: Denah,
  },
  {
    id: 6,
    type: "B7",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "64",
    denah: Denah,
  },
  {
    id: 7,
    type: "B8",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "65",
    denah: Denah,
  },
  {
    id: 8,
    type: "C3",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "66",
    denah: Denah,
  },
  {
    id: 9,
    type: "C7",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "108",
    denah: Denah,
  },
  {
    id: 10,
    type: "A2",
    name: "Ginasteel Kavling",
    poin1: "✅  1 menit ke Wisata embung giriroto",
    poin2: "✅  1 menit ke SDN 3 Giriroto",
    poin3: "✅  5 menit ke SPBU Gondangrejo",
    poin4: "✅  5 menit ke Jl Raya Solo - Purwodadi",
    poin5: "✅  5 menit ke Jalan  Raya Ngemplak-Kalioso",
    poin6: "✅  4 menit ke Taman Qris",
    poin7: "✅ 15 Asrama haji donohudan",
    poin8: "✅ 15 menit ke Gerbang Toll Ngemplak",
    poin9: "✅ 15 menit ke Gerbang Toll Gondangrejo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling2,
    imageLg: Kavling2,
    country: "Boyolali",
    daerah: "Kismoyoso",
    address: "Kismoyoso, Ngemplak, Boyolali",
    price: "78",
    denah: Denah2,
  },
];

export const dealDone = [
  {
    id: 1,
    img: gambar1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat.",
  },
  {
    id: 2,
    img: gambar2,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat.",
  },
  {
    id: 3,
    img: gambar3,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat.",
  },
  {
    id: 4,
    img: gambar4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat.",
  },
  {
    id: 5,
    img: gambar5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat.",
  },
  {
    id: 6,
    img: gambar6,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat.",
  },
  {
    id: 7,
    img: gambar7,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat.",
  },
];

export const testimoni = [
  {
    id: 1,
    img: person1,
    text: "Amanah, dijamin top deh. pilih yang oke oke aja",
  },
  {
    id: 2,
    img: person1,
    text: "Pelayanannya baik, fast respon. Pokoknya saya saranin beli tanah disini deh",
  },
  {
    id: 3,
    img: person1,
    text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut ullam eaque",
  },
  {
    id: 4,
    img: person1,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat.",
  },
  {
    id: 5,
    img: person1,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat.",
  },
  {
    id: 6,
    img: person1,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat.",
  },
];
