// import kavling
import Kavling1 from "./assets/img/KEYONGAN/kavling keyongan.jpg";
import Denah from "./assets/img/KEYONGAN/DENAH KEYONGAN.png";
import Kavling2 from "./assets/img/NGINGAS/kavling ngingas.jpg";
import Denah2 from "./assets/img/NGINGAS/DENAH NGINGAS.png";
import Kavling3 from "./assets/img/POJOK/kavling pojok.jpg";
import Denah3 from "./assets/img/POJOK/DENAH POJOK 2NOGOSARI 2.png";
import Kavling4 from "./assets/img/POJOK1/Lokasi.jpg";
import Denah4 from "./assets/img/POJOK1/DENAH POJOK LAWAS.png";
import Kavling5 from "./assets/img/KEBAKRAMAT/lokasi.jpg";
import Denah5 from "./assets/img/KEBAKRAMAT/DENAH KAVLING KEBAKKRAMAT.png";
import Kavling6 from "./assets/img/TUBAN LOR2/lokasi.jpg";
import Denah6 from "./assets/img/TUBAN LOR2/DENAH TUBAN LOR 3.png";

//dealdone
import gambar1 from "./assets/img/dealdone/deal1.jpg";
import gambar2 from "./assets/img/dealdone/deal2.jpg";
import gambar3 from "./assets/img/dealdone/deal3.jpg";
import gambar4 from "./assets/img/dealdone/deal4.jpg";
import gambar5 from "./assets/img/dealdone/deal5.jpg";
import gambar6 from "./assets/img/dealdone/deal6.jpg";
import gambar7 from "./assets/img/dealdone/deal7.jpg";
import gambar8 from "./assets/img/dealdone/deal8.jpg";

//testi
import person1 from "./assets/img/testimoni/testi2.png";
import person2 from "./assets/img/testimoni/testi1.jpg";
import person3 from "./assets/img/testimoni/testi3.png";
import person4 from "./assets/img/testimoni/testi4.png";

export const housesData = [
  {
    id: 1,
    type: "A3",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Kavling Murah di Boyolali, 3 menit ke SPBU Nogosari, 5 menit ke Pasar Nogosari, cocok untuk investasi atau Nabung Tanah, Free biaya biaya, lokasi asri, mobil masuk, dari Jl. Simo-Kalioso masuk 350m Keyongan, Nogosari, Boyolali",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "70",
    denah: Denah,
  },
  {
    id: 2,
    type: "B2",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Kavling Murah di Boyolali, 3 menit ke SPBU Nogosari, 5 menit ke Pasar Nogosari, cocok untuk investasi atau Nabung Tanah, Free biaya biaya, lokasi asri, mobil masuk, dari Jl. Simo-Kalioso masuk 350m Keyongan, Nogosari, Boyolali",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "52",
    denah: Denah,
  },
  {
    id: 3,
    type: "B3",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Kavling Murah di Boyolali, 3 menit ke SPBU Nogosari, 5 menit ke Pasar Nogosari, cocok untuk investasi atau Nabung Tanah, Free biaya biaya, lokasi asri, mobil masuk, dari Jl. Simo-Kalioso masuk 350m Keyongan, Nogosari, Boyolali",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "59",
    denah: Denah,
  },
  {
    id: 4,
    type: "B4",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Kavling Murah di Boyolali, 3 menit ke SPBU Nogosari, 5 menit ke Pasar Nogosari, cocok untuk investasi atau Nabung Tanah, Free biaya biaya, lokasi asri, mobil masuk, dari Jl. Simo-Kalioso masuk 350m Keyongan, Nogosari, Boyolali",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "59",
    denah: Denah,
  },
  {
    id: 5,
    type: "B5",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Kavling Murah di Boyolali, 3 menit ke SPBU Nogosari, 5 menit ke Pasar Nogosari, cocok untuk investasi atau Nabung Tanah, Free biaya biaya, lokasi asri, mobil masuk, dari Jl. Simo-Kalioso masuk 350m Keyongan, Nogosari, Boyolali",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "60",
    denah: Denah,
  },
  {
    id: 6,
    type: "B7",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Kavling Murah di Boyolali, 3 menit ke SPBU Nogosari, 5 menit ke Pasar Nogosari, cocok untuk investasi atau Nabung Tanah, Free biaya biaya, lokasi asri, mobil masuk, dari Jl. Simo-Kalioso masuk 350m Keyongan, Nogosari, Boyolali",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "64",
    denah: Denah,
  },
  {
    id: 7,
    type: "B8",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Kavling Murah di Boyolali, 3 menit ke SPBU Nogosari, 5 menit ke Pasar Nogosari, cocok untuk investasi atau Nabung Tanah, Free biaya biaya, lokasi asri, mobil masuk, dari Jl. Simo-Kalioso masuk 350m Keyongan, Nogosari, Boyolali",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "65",
    denah: Denah,
  },
  {
    id: 8,
    type: "C3",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Kavling Murah di Boyolali, 3 menit ke SPBU Nogosari, 5 menit ke Pasar Nogosari, cocok untuk investasi atau Nabung Tanah, Free biaya biaya, lokasi asri, mobil masuk, dari Jl. Simo-Kalioso masuk 350m Keyongan, Nogosari, Boyolali",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "66",
    denah: Denah,
  },
  {
    id: 9,
    type: "C7",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Kavling Murah di Boyolali, 3 menit ke SPBU Nogosari, 5 menit ke Pasar Nogosari, cocok untuk investasi atau Nabung Tanah, Free biaya biaya, lokasi asri, mobil masuk, dari Jl. Simo-Kalioso masuk 350m Keyongan, Nogosari, Boyolali",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "108",
    denah: Denah,
  },
  {
    id: 10,
    type: "A2",
    name: "Ginasteel Kavling",
    poin1: "✅  1 menit ke Wisata embung giriroto",
    poin2: "✅  1 menit ke SDN 3 Giriroto",
    poin3: "✅  5 menit ke SPBU Gondangrejo",
    poin4: "✅  5 menit ke Jl Raya Solo - Purwodadi",
    poin5: "✅  5 menit ke Jalan  Raya Ngemplak-Kalioso",
    poin6: "✅  4 menit ke Taman Qris",
    poin7: "✅ 15 Asrama haji donohudan",
    poin8: "✅ 15 menit ke Gerbang Toll Ngemplak",
    poin9: "✅ 15 menit ke Gerbang Toll Gondangrejo",
    description:
      "Tanah Kavling Siap bangun 5 MENIT dari SPBU GONDANGREJO.. Atau JL Raya SOLO - PURWODADI..",
    image: Kavling2,
    imageLg: Kavling2,
    country: "Boyolali",
    daerah: "Kismoyoso",
    address: "Kismoyoso, Ngemplak, Boyolali",
    price: "78",
    denah: Denah2,
  },
  {
    id: 11,
    type: "B1",
    name: "Ginasteel Kavling",
    poin1: "✅  1 menit ke Wisata embung giriroto",
    poin2: "✅  1 menit ke SDN 3 Giriroto",
    poin3: "✅  5 menit ke SPBU Gondangrejo",
    poin4: "✅  5 menit ke Jl Raya Solo - Purwodadi",
    poin5: "✅  5 menit ke Jalan  Raya Ngemplak-Kalioso",
    poin6: "✅  4 menit ke Taman Qris",
    poin7: "✅ 15 Asrama haji donohudan",
    poin8: "✅ 15 menit ke Gerbang Toll Ngemplak",
    poin9: "✅ 15 menit ke Gerbang Toll Gondangrejo",
    description:
      "Tanah Kavling Siap bangun 5 MENIT dari SPBU GONDANGREJO.. Atau JL Raya SOLO - PURWODADI..",
    image: Kavling2,
    imageLg: Kavling2,
    country: "Boyolali",
    daerah: "Kismoyoso",
    address: "Kismoyoso, Ngemplak, Boyolali",
    price: "78",
    denah: Denah2,
  },
  {
    id: 12,
    type: "B2",
    name: "Ginasteel Kavling",
    poin1: "✅  1 menit ke Wisata embung giriroto",
    poin2: "✅  1 menit ke SDN 3 Giriroto",
    poin3: "✅  5 menit ke SPBU Gondangrejo",
    poin4: "✅  5 menit ke Jl Raya Solo - Purwodadi",
    poin5: "✅  5 menit ke Jalan  Raya Ngemplak-Kalioso",
    poin6: "✅  4 menit ke Taman Qris",
    poin7: "✅ 15 Asrama haji donohudan",
    poin8: "✅ 15 menit ke Gerbang Toll Ngemplak",
    poin9: "✅ 15 menit ke Gerbang Toll Gondangrejo",
    description:
      "Tanah Kavling Siap bangun 5 MENIT dari SPBU GONDANGREJO.. Atau JL Raya SOLO - PURWODADI..",
    image: Kavling2,
    imageLg: Kavling2,
    country: "Boyolali",
    daerah: "Kismoyoso",
    address: "Kismoyoso, Ngemplak, Boyolali",
    price: "84",
    denah: Denah2,
  },
  {
    id: 13,
    type: "B4",
    name: "Ginasteel Kavling",
    poin1: "✅  1 menit ke Wisata embung giriroto",
    poin2: "✅  1 menit ke SDN 3 Giriroto",
    poin3: "✅  5 menit ke SPBU Gondangrejo",
    poin4: "✅  5 menit ke Jl Raya Solo - Purwodadi",
    poin5: "✅  5 menit ke Jalan  Raya Ngemplak-Kalioso",
    poin6: "✅  4 menit ke Taman Qris",
    poin7: "✅ 15 Asrama haji donohudan",
    poin8: "✅ 15 menit ke Gerbang Toll Ngemplak",
    poin9: "✅ 15 menit ke Gerbang Toll Gondangrejo",
    description:
      "Tanah Kavling Siap bangun 5 MENIT dari SPBU GONDANGREJO.. Atau JL Raya SOLO - PURWODADI..",
    image: Kavling2,
    imageLg: Kavling2,
    country: "Boyolali",
    daerah: "Kismoyoso",
    address: "Kismoyoso, Ngemplak, Boyolali",
    price: "70",
    denah: Denah2,
  },
  {
    id: 14,
    type: "B5",
    name: "Ginasteel Kavling",
    poin1: "✅  1 menit ke Wisata embung giriroto",
    poin2: "✅  1 menit ke SDN 3 Giriroto",
    poin3: "✅  5 menit ke SPBU Gondangrejo",
    poin4: "✅  5 menit ke Jl Raya Solo - Purwodadi",
    poin5: "✅  5 menit ke Jalan  Raya Ngemplak-Kalioso",
    poin6: "✅  4 menit ke Taman Qris",
    poin7: "✅ 15 Asrama haji donohudan",
    poin8: "✅ 15 menit ke Gerbang Toll Ngemplak",
    poin9: "✅ 15 menit ke Gerbang Toll Gondangrejo",
    description:
      "Tanah Kavling Siap bangun 5 MENIT dari SPBU GONDANGREJO.. Atau JL Raya SOLO - PURWODADI..",
    image: Kavling2,
    imageLg: Kavling2,
    country: "Boyolali",
    daerah: "Kismoyoso",
    address: "Kismoyoso, Ngemplak, Boyolali",
    price: "70",
    denah: Denah2,
  },
  {
    id: 15,
    type: "A3",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "69",
    denah: Denah3,
  },
  {
    id: 16,
    type: "A4",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "69",
    denah: Denah3,
  },
  {
    id: 17,
    type: "A5",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "69",
    denah: Denah3,
  },
  {
    id: 18,
    type: "A6",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "56",
    denah: Denah3,
  },
  {
    id: 19,
    type: "A7",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "60",
    denah: Denah3,
  },
  {
    id: 20,
    type: "A8",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "60",
    denah: Denah3,
  },
  {
    id: 21,
    type: "A9",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "60",
    denah: Denah3,
  },
  {
    id: 22,
    type: "B3",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 23,
    type: "B4",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 24,
    type: "B5",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 25,
    type: "B6",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 26,
    type: "B7",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 27,
    type: "B8",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 28,
    type: "B9",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 29,
    type: "B10",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 30,
    type: "B11",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "67",
    denah: Denah3,
  },
  {
    id: 31,
    type: "A1",
    name: "Pojok1 Kavling",
    poin1: "✅  400 mtr ke Jl. Raya Simo - Kalioso",
    poin2: "✅  1 menit Masjid Baiturrachman",
    poin3: "✅  1 menit SDN Weru",
    poin4: "✅  3 menit Tugu Punokawan",
    poin5: "✅  4 menit SPBU Nogosari",
    poin6: "✅  5 menit Pasar Nogosari",
    poin7: "✅  5 menit Puskesmas Nogosari",
    poin8: "✅  20 menit Bandara Adi Soemarmo",
    description:
      "KavlingSHM Pekarangan siap bangun.. Lokasi pedesaan asri, padat penduduk, nan sejuk..",
    image: Kavling4,
    imageLg: Kavling4,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "62",
    denah: Denah4,
  },
  {
    id: 32,
    type: "A2",
    name: "Pojok1 Kavling",
    poin1: "✅  400 mtr ke Jl. Raya Simo - Kalioso",
    poin2: "✅  1 menit Masjid Baiturrachman",
    poin3: "✅  1 menit SDN Weru",
    poin4: "✅  3 menit Tugu Punokawan",
    poin5: "✅  4 menit SPBU Nogosari",
    poin6: "✅  5 menit Pasar Nogosari",
    poin7: "✅  5 menit Puskesmas Nogosari",
    poin8: "✅  20 menit Bandara Adi Soemarmo",
    description:
      "KavlingSHM Pekarangan siap bangun.. Lokasi pedesaan asri, padat penduduk, nan sejuk..",
    image: Kavling4,
    imageLg: Kavling4,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "73",
    denah: Denah4,
  },
  {
    id: 33,
    type: "B2",
    name: "Pojok1 Kavling",
    poin1: "✅  400 mtr ke Jl. Raya Simo - Kalioso",
    poin2: "✅  1 menit Masjid Baiturrachman",
    poin3: "✅  1 menit SDN Weru",
    poin4: "✅  3 menit Tugu Punokawan",
    poin5: "✅  4 menit SPBU Nogosari",
    poin6: "✅  5 menit Pasar Nogosari",
    poin7: "✅  5 menit Puskesmas Nogosari",
    poin8: "✅  20 menit Bandara Adi Soemarmo",
    description:
      "KavlingSHM Pekarangan siap bangun.. Lokasi pedesaan asri, padat penduduk, nan sejuk..",
    image: Kavling4,
    imageLg: Kavling4,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "60",
    denah: Denah4,
  },
  {
    id: 34,
    type: "B6",
    name: "Pojok1 Kavling",
    poin1: "✅  400 mtr ke Jl. Raya Simo - Kalioso",
    poin2: "✅  1 menit Masjid Baiturrachman",
    poin3: "✅  1 menit SDN Weru",
    poin4: "✅  3 menit Tugu Punokawan",
    poin5: "✅  4 menit SPBU Nogosari",
    poin6: "✅  5 menit Pasar Nogosari",
    poin7: "✅  5 menit Puskesmas Nogosari",
    poin8: "✅  20 menit Bandara Adi Soemarmo",
    description:
      "KavlingSHM Pekarangan siap bangun.. Lokasi pedesaan asri, padat penduduk, nan sejuk..",
    image: Kavling4,
    imageLg: Kavling4,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "60",
    denah: Denah4,
  },
  {
    id: 35,
    type: "A1",
    name: "Kebakkramat Kavling",
    poin1: "✅  1 Menit ke SMPN 3 Kebakkramat",
    poin2: "✅  4 Menit ke Kantor kepala desa Alastuo",
    poin3: "✅  5 Menit ke Pasar Pagi Kaling",
    poin4: "✅  10 Menit ke Koramil Tasikmadu",
    poin5: "✅  12 Menit ke Toll Gate Karanganyar",
    poin6: "✅  12 Menit ke RSU indo sehat",
    poin7: "✅  12 Menit ke Puskesmas Tasikmadu",
    poin8: "✅  15 Menit ke Solo",
    description:
      "Membeli tanah bukan hanya tentang lokasi tanah sesuai... melainkan berkaitan dengan seritikat.. jangan tergiur dengan harga yang sangat murah tetapi sertifikat tidak ada... Oleh karena itu percayakan SIMPLY PROPERTY sebagai developer tempat anda membeli tanah. Pasti prosesnya, Pasti Legalnya, Pasti jadi sertfifikatnya",
    image: Kavling5,
    imageLg: Kavling5,
    country: "Karanganyar",
    daerah: "Kebakkramat",
    address: "Kebakkramat, Karanganyar",
    price: "63",
    denah: Denah5,
  },
  {
    id: 36,
    type: "A2",
    name: "Kebakkramat Kavling",
    poin1: "✅  1 Menit ke SMPN 3 Kebakkramat",
    poin2: "✅  4 Menit ke Kantor kepala desa Alastuo",
    poin3: "✅  5 Menit ke Pasar Pagi Kaling",
    poin4: "✅  10 Menit ke Koramil Tasikmadu",
    poin5: "✅  12 Menit ke Toll Gate Karanganyar",
    poin6: "✅  12 Menit ke RSU indo sehat",
    poin7: "✅  12 Menit ke Puskesmas Tasikmadu",
    poin8: "✅  15 Menit ke Solo",
    description:
      "Membeli tanah bukan hanya tentang lokasi tanah sesuai... melainkan berkaitan dengan seritikat.. jangan tergiur dengan harga yang sangat murah tetapi sertifikat tidak ada... Oleh karena itu percayakan SIMPLY PROPERTY sebagai developer tempat anda membeli tanah. Pasti prosesnya, Pasti Legalnya, Pasti jadi sertfifikatnya",
    image: Kavling5,
    imageLg: Kavling5,
    country: "Karanganyar",
    daerah: "Kebakkramat",
    address: "Kebakkramat, Karanganyar",
    price: "67",
    denah: Denah5,
  },
  {
    id: 37,
    type: "A3",
    name: "Kebakkramat Kavling",
    poin1: "✅  1 Menit ke SMPN 3 Kebakkramat",
    poin2: "✅  4 Menit ke Kantor kepala desa Alastuo",
    poin3: "✅  5 Menit ke Pasar Pagi Kaling",
    poin4: "✅  10 Menit ke Koramil Tasikmadu",
    poin5: "✅  12 Menit ke Toll Gate Karanganyar",
    poin6: "✅  12 Menit ke RSU indo sehat",
    poin7: "✅  12 Menit ke Puskesmas Tasikmadu",
    poin8: "✅  15 Menit ke Solo",
    description:
      "Membeli tanah bukan hanya tentang lokasi tanah sesuai... melainkan berkaitan dengan seritikat.. jangan tergiur dengan harga yang sangat murah tetapi sertifikat tidak ada... Oleh karena itu percayakan SIMPLY PROPERTY sebagai developer tempat anda membeli tanah. Pasti prosesnya, Pasti Legalnya, Pasti jadi sertfifikatnya",
    image: Kavling5,
    imageLg: Kavling5,
    country: "Karanganyar",
    daerah: "Kebakkramat",
    address: "Kebakkramat, Karanganyar",
    price: "61",
    denah: Denah5,
  },
  {
    id: 38,
    type: "A4",
    name: "Kebakkramat Kavling",
    poin1: "✅  1 Menit ke SMPN 3 Kebakkramat",
    poin2: "✅  4 Menit ke Kantor kepala desa Alastuo",
    poin3: "✅  5 Menit ke Pasar Pagi Kaling",
    poin4: "✅  10 Menit ke Koramil Tasikmadu",
    poin5: "✅  12 Menit ke Toll Gate Karanganyar",
    poin6: "✅  12 Menit ke RSU indo sehat",
    poin7: "✅  12 Menit ke Puskesmas Tasikmadu",
    poin8: "✅  15 Menit ke Solo",
    description:
      "Membeli tanah bukan hanya tentang lokasi tanah sesuai... melainkan berkaitan dengan seritikat.. jangan tergiur dengan harga yang sangat murah tetapi sertifikat tidak ada... Oleh karena itu percayakan SIMPLY PROPERTY sebagai developer tempat anda membeli tanah. Pasti prosesnya, Pasti Legalnya, Pasti jadi sertfifikatnya",
    image: Kavling5,
    imageLg: Kavling5,
    country: "Karanganyar",
    daerah: "Kebakkramat",
    address: "Kebakkramat, Karanganyar",
    price: "53",
    denah: Denah5,
  },
  {
    id: 39,
    type: "A5",
    name: "Kebakkramat Kavling",
    poin1: "✅  1 Menit ke SMPN 3 Kebakkramat",
    poin2: "✅  4 Menit ke Kantor kepala desa Alastuo",
    poin3: "✅  5 Menit ke Pasar Pagi Kaling",
    poin4: "✅  10 Menit ke Koramil Tasikmadu",
    poin5: "✅  12 Menit ke Toll Gate Karanganyar",
    poin6: "✅  12 Menit ke RSU indo sehat",
    poin7: "✅  12 Menit ke Puskesmas Tasikmadu",
    poin8: "✅  15 Menit ke Solo",
    description:
      "Membeli tanah bukan hanya tentang lokasi tanah sesuai... melainkan berkaitan dengan seritikat.. jangan tergiur dengan harga yang sangat murah tetapi sertifikat tidak ada... Oleh karena itu percayakan SIMPLY PROPERTY sebagai developer tempat anda membeli tanah. Pasti prosesnya, Pasti Legalnya, Pasti jadi sertfifikatnya",
    image: Kavling5,
    imageLg: Kavling5,
    country: "Karanganyar",
    daerah: "Kebakkramat",
    address: "Kebakkramat, Karanganyar",
    price: "62",
    denah: Denah5,
  },
  {
    id: 40,
    type: "B1",
    name: "Kebakkramat Kavling",
    poin1: "✅  1 Menit ke SMPN 3 Kebakkramat",
    poin2: "✅  4 Menit ke Kantor kepala desa Alastuo",
    poin3: "✅  5 Menit ke Pasar Pagi Kaling",
    poin4: "✅  10 Menit ke Koramil Tasikmadu",
    poin5: "✅  12 Menit ke Toll Gate Karanganyar",
    poin6: "✅  12 Menit ke RSU indo sehat",
    poin7: "✅  12 Menit ke Puskesmas Tasikmadu",
    poin8: "✅  15 Menit ke Solo",
    description:
      "Membeli tanah bukan hanya tentang lokasi tanah sesuai... melainkan berkaitan dengan seritikat.. jangan tergiur dengan harga yang sangat murah tetapi sertifikat tidak ada... Oleh karena itu percayakan SIMPLY PROPERTY sebagai developer tempat anda membeli tanah. Pasti prosesnya, Pasti Legalnya, Pasti jadi sertfifikatnya",
    image: Kavling5,
    imageLg: Kavling5,
    country: "Karanganyar",
    daerah: "Kebakkramat",
    address: "Kebakkramat, Karanganyar",
    price: "64",
    denah: Denah5,
  },
  {
    id: 41,
    type: "B2",
    name: "Kebakkramat Kavling",
    poin1: "✅  1 Menit ke SMPN 3 Kebakkramat",
    poin2: "✅  4 Menit ke Kantor kepala desa Alastuo",
    poin3: "✅  5 Menit ke Pasar Pagi Kaling",
    poin4: "✅  10 Menit ke Koramil Tasikmadu",
    poin5: "✅  12 Menit ke Toll Gate Karanganyar",
    poin6: "✅  12 Menit ke RSU indo sehat",
    poin7: "✅  12 Menit ke Puskesmas Tasikmadu",
    poin8: "✅  15 Menit ke Solo",
    description:
      "Membeli tanah bukan hanya tentang lokasi tanah sesuai... melainkan berkaitan dengan seritikat.. jangan tergiur dengan harga yang sangat murah tetapi sertifikat tidak ada... Oleh karena itu percayakan SIMPLY PROPERTY sebagai developer tempat anda membeli tanah. Pasti prosesnya, Pasti Legalnya, Pasti jadi sertfifikatnya",
    image: Kavling5,
    imageLg: Kavling5,
    country: "Karanganyar",
    daerah: "Kebakkramat",
    address: "Kebakkramat, Karanganyar",
    price: "61",
    denah: Denah5,
  },
  {
    id: 42,
    type: "B3",
    name: "Kebakkramat Kavling",
    poin1: "✅  1 Menit ke SMPN 3 Kebakkramat",
    poin2: "✅  4 Menit ke Kantor kepala desa Alastuo",
    poin3: "✅  5 Menit ke Pasar Pagi Kaling",
    poin4: "✅  10 Menit ke Koramil Tasikmadu",
    poin5: "✅  12 Menit ke Toll Gate Karanganyar",
    poin6: "✅  12 Menit ke RSU indo sehat",
    poin7: "✅  12 Menit ke Puskesmas Tasikmadu",
    poin8: "✅  15 Menit ke Solo",
    description:
      "Membeli tanah bukan hanya tentang lokasi tanah sesuai... melainkan berkaitan dengan seritikat.. jangan tergiur dengan harga yang sangat murah tetapi sertifikat tidak ada... Oleh karena itu percayakan SIMPLY PROPERTY sebagai developer tempat anda membeli tanah. Pasti prosesnya, Pasti Legalnya, Pasti jadi sertfifikatnya",
    image: Kavling5,
    imageLg: Kavling5,
    country: "Karanganyar",
    daerah: "Kebakkramat",
    address: "Kebakkramat, Karanganyar",
    price: "53",
    denah: Denah5,
  },
  {
    id: 43,
    type: "B4",
    name: "Kebakkramat Kavling",
    poin1: "✅  1 Menit ke SMPN 3 Kebakkramat",
    poin2: "✅  4 Menit ke Kantor kepala desa Alastuo",
    poin3: "✅  5 Menit ke Pasar Pagi Kaling",
    poin4: "✅  10 Menit ke Koramil Tasikmadu",
    poin5: "✅  12 Menit ke Toll Gate Karanganyar",
    poin6: "✅  12 Menit ke RSU indo sehat",
    poin7: "✅  12 Menit ke Puskesmas Tasikmadu",
    poin8: "✅  15 Menit ke Solo",
    description:
      "Membeli tanah bukan hanya tentang lokasi tanah sesuai... melainkan berkaitan dengan seritikat.. jangan tergiur dengan harga yang sangat murah tetapi sertifikat tidak ada... Oleh karena itu percayakan SIMPLY PROPERTY sebagai developer tempat anda membeli tanah. Pasti prosesnya, Pasti Legalnya, Pasti jadi sertfifikatnya",
    image: Kavling5,
    imageLg: Kavling5,
    country: "Karanganyar",
    daerah: "Kebakkramat",
    address: "Kebakkramat, Karanganyar",
    price: "53",
    denah: Denah5,
  },
  {
    id: 44,
    type: "C1",
    name: "Kebakkramat Kavling",
    poin1: "✅  1 Menit ke SMPN 3 Kebakkramat",
    poin2: "✅  4 Menit ke Kantor kepala desa Alastuo",
    poin3: "✅  5 Menit ke Pasar Pagi Kaling",
    poin4: "✅  10 Menit ke Koramil Tasikmadu",
    poin5: "✅  12 Menit ke Toll Gate Karanganyar",
    poin6: "✅  12 Menit ke RSU indo sehat",
    poin7: "✅  12 Menit ke Puskesmas Tasikmadu",
    poin8: "✅  15 Menit ke Solo",
    description:
      "Membeli tanah bukan hanya tentang lokasi tanah sesuai... melainkan berkaitan dengan seritikat.. jangan tergiur dengan harga yang sangat murah tetapi sertifikat tidak ada... Oleh karena itu percayakan SIMPLY PROPERTY sebagai developer tempat anda membeli tanah. Pasti prosesnya, Pasti Legalnya, Pasti jadi sertfifikatnya",
    image: Kavling5,
    imageLg: Kavling5,
    country: "Karanganyar",
    daerah: "Kebakkramat",
    address: "Kebakkramat, Karanganyar",
    price: "61",
    denah: Denah5,
  },
  {
    id: 45,
    type: "C2",
    name: "Kebakkramat Kavling",
    poin1: "✅  1 Menit ke SMPN 3 Kebakkramat",
    poin2: "✅  4 Menit ke Kantor kepala desa Alastuo",
    poin3: "✅  5 Menit ke Pasar Pagi Kaling",
    poin4: "✅  10 Menit ke Koramil Tasikmadu",
    poin5: "✅  12 Menit ke Toll Gate Karanganyar",
    poin6: "✅  12 Menit ke RSU indo sehat",
    poin7: "✅  12 Menit ke Puskesmas Tasikmadu",
    poin8: "✅  15 Menit ke Solo",
    description:
      "Membeli tanah bukan hanya tentang lokasi tanah sesuai... melainkan berkaitan dengan seritikat.. jangan tergiur dengan harga yang sangat murah tetapi sertifikat tidak ada... Oleh karena itu percayakan SIMPLY PROPERTY sebagai developer tempat anda membeli tanah. Pasti prosesnya, Pasti Legalnya, Pasti jadi sertfifikatnya",
    image: Kavling5,
    imageLg: Kavling5,
    country: "Karanganyar",
    daerah: "Kebakkramat",
    address: "Kebakkramat, Karanganyar",
    price: "64",
    denah: Denah5,
  },
  {
    id: 46,
    type: "C3",
    name: "Kebakkramat Kavling",
    poin1: "✅  1 Menit ke SMPN 3 Kebakkramat",
    poin2: "✅  4 Menit ke Kantor kepala desa Alastuo",
    poin3: "✅  5 Menit ke Pasar Pagi Kaling",
    poin4: "✅  10 Menit ke Koramil Tasikmadu",
    poin5: "✅  12 Menit ke Toll Gate Karanganyar",
    poin6: "✅  12 Menit ke RSU indo sehat",
    poin7: "✅  12 Menit ke Puskesmas Tasikmadu",
    poin8: "✅  15 Menit ke Solo",
    description:
      "Membeli tanah bukan hanya tentang lokasi tanah sesuai... melainkan berkaitan dengan seritikat.. jangan tergiur dengan harga yang sangat murah tetapi sertifikat tidak ada... Oleh karena itu percayakan SIMPLY PROPERTY sebagai developer tempat anda membeli tanah. Pasti prosesnya, Pasti Legalnya, Pasti jadi sertfifikatnya",
    image: Kavling5,
    imageLg: Kavling5,
    country: "Karanganyar",
    daerah: "Kebakkramat",
    address: "Kebakkramat, Karanganyar",
    price: "78",
    denah: Denah5,
  },
  {
    id: 47,
    type: "C4",
    name: "Kebakkramat Kavling",
    poin1: "✅  1 Menit ke SMPN 3 Kebakkramat",
    poin2: "✅  4 Menit ke Kantor kepala desa Alastuo",
    poin3: "✅  5 Menit ke Pasar Pagi Kaling",
    poin4: "✅  10 Menit ke Koramil Tasikmadu",
    poin5: "✅  12 Menit ke Toll Gate Karanganyar",
    poin6: "✅  12 Menit ke RSU indo sehat",
    poin7: "✅  12 Menit ke Puskesmas Tasikmadu",
    poin8: "✅  15 Menit ke Solo",
    description:
      "Membeli tanah bukan hanya tentang lokasi tanah sesuai... melainkan berkaitan dengan seritikat.. jangan tergiur dengan harga yang sangat murah tetapi sertifikat tidak ada... Oleh karena itu percayakan SIMPLY PROPERTY sebagai developer tempat anda membeli tanah. Pasti prosesnya, Pasti Legalnya, Pasti jadi sertfifikatnya",
    image: Kavling5,
    imageLg: Kavling5,
    country: "Karanganyar",
    daerah: "Kebakkramat",
    address: "Kebakkramat, Karanganyar",
    price: "78",
    denah: Denah5,
  },
  {
    id: 48,
    type: "D1",
    name: "Kebakkramat Kavling",
    poin1: "✅  1 Menit ke SMPN 3 Kebakkramat",
    poin2: "✅  4 Menit ke Kantor kepala desa Alastuo",
    poin3: "✅  5 Menit ke Pasar Pagi Kaling",
    poin4: "✅  10 Menit ke Koramil Tasikmadu",
    poin5: "✅  12 Menit ke Toll Gate Karanganyar",
    poin6: "✅  12 Menit ke RSU indo sehat",
    poin7: "✅  12 Menit ke Puskesmas Tasikmadu",
    poin8: "✅  15 Menit ke Solo",
    description:
      "Membeli tanah bukan hanya tentang lokasi tanah sesuai... melainkan berkaitan dengan seritikat.. jangan tergiur dengan harga yang sangat murah tetapi sertifikat tidak ada... Oleh karena itu percayakan SIMPLY PROPERTY sebagai developer tempat anda membeli tanah. Pasti prosesnya, Pasti Legalnya, Pasti jadi sertfifikatnya",
    image: Kavling5,
    imageLg: Kavling5,
    country: "Karanganyar",
    daerah: "Kebakkramat",
    address: "Kebakkramat, Karanganyar",
    price: "93",
    denah: Denah5,
  },
  {
    id: 49,
    type: "A1",
    name: "Tanah Tuban Lor 2",
    poin1: "✅  2 menit Apotik Kalioso",
    poin2: "✅  2 menit Pasar Kalioso",
    poin3: "✅  2 menit SDN 2 Tuban",
    poin4: "✅  2 menit Terminal Kalioso",
    poin5: "✅  3 menit Pasar Sapi",
    poin6: "✅  3 menit Koramil Gondangrejo",
    poin7: "✅  3 menit Stasiun Kalioso",
    poin8: "✅  4 menit Kantor Kecamatan Gondangrejo",
    poin9: "✅ 5 menit SPBU Kalijambe",
    poin10: "✅ 8 menit SPBU Gondangrejo",
    poin11: "✅ 15 menit Tol Gate Gondangrejo",
    description:
      "Tanah strategis di daerah Tuban, (Kalioso) yang sangat dekat dengan jalan Solo-Purwodadi. Tanah ini memiliki luas 72 m2 dengan status hak milik (SHM PEKARANGAN) yang jelas dan aman. Terletak di area lingkungan yang islami dan nyaman, tanah ini menawarkan potensi yang menarik untuk investasi ataupun untuk hunian keluarga anda.",
    image: Kavling6,
    imageLg: Kavling6,
    country: "Karanganyar",
    daerah: "Gondangrejo",
    address: "Gondangrejo, Karanganyar",
    price: "108",
    denah: Denah6,
  },
];

export const dealDone = [
  {
    id: 1,
    img: gambar1,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
  {
    id: 2,
    img: gambar2,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
  {
    id: 3,
    img: gambar3,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
  {
    id: 4,
    img: gambar4,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
  {
    id: 5,
    img: gambar5,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
  {
    id: 6,
    img: gambar6,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
  {
    id: 7,
    img: gambar7,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
  {
    id: 8,
    img: gambar8,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
];

export const testimoni = [
  {
    id: 1,
    img: person1,
    text: "Alhamdulillah. timnya ramah, owner-nya juga ramah, dan harganya pun juga ramah",
  },
  {
    id: 2,
    img: person2,
    text: "Admin-adminnya orangnya baik, sertifikatnya juga cepet sesuai dengan schedule",
  },
  {
    id: 3,
    img: person3,
    text: "Pembayarannya mudah, bisa cash atau angsur. Angsurannya juga mudah. Timnya juga baik",
  },
  {
    id: 4,
    img: person4,
    text: "Admin-adminnya orangnya baik, sertifikatnya juga cepet sesuai dengan schedule",
  },
];
