// import kavling
import Kavling1 from "./assets/img/KEYONGAN/kavling keyongan.jpg";
import Denah from "./assets/img/KEYONGAN/DENAH KEYONGAN.png";
import Kavling2 from "./assets/img/NGINGAS/kavling ngingas.jpg";
import Denah2 from "./assets/img/NGINGAS/DENAH NGINGAS.png";
import Kavling3 from "./assets/img/POJOK/kavling pojok.jpg";
import Denah3 from "./assets/img/POJOK/DENAH POJOK 2NOGOSARI 2.png";

//dealdone
import gambar1 from "./assets/img/dealdone/deal1.jpg";
import gambar2 from "./assets/img/dealdone/deal2.jpg";
import gambar3 from "./assets/img/dealdone/deal3.jpg";
import gambar4 from "./assets/img/dealdone/deal4.jpg";
import gambar5 from "./assets/img/dealdone/deal5.jpg";
import gambar6 from "./assets/img/dealdone/deal6.jpg";
import gambar7 from "./assets/img/dealdone/deal7.jpg";
import gambar8 from "./assets/img/dealdone/deal8.jpg";

//testi
import person1 from "./assets/img/testimoni/testi2.png";
import person2 from "./assets/img/testimoni/testi1.jpg";
import person3 from "./assets/img/testimoni/testi3.png";
import person4 from "./assets/img/testimoni/testi4.png";

export const housesData = [
  {
    id: 1,
    type: "A3",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "70",
    denah: Denah,
  },
  {
    id: 2,
    type: "B2",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "52",
    denah: Denah,
  },
  {
    id: 3,
    type: "B3",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "59",
    denah: Denah,
  },
  {
    id: 4,
    type: "B4",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "59",
    denah: Denah,
  },
  {
    id: 5,
    type: "B5",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "60",
    denah: Denah,
  },
  {
    id: 6,
    type: "B7",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "64",
    denah: Denah,
  },
  {
    id: 7,
    type: "B8",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "65",
    denah: Denah,
  },
  {
    id: 8,
    type: "C3",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "66",
    denah: Denah,
  },
  {
    id: 9,
    type: "C7",
    name: "Keyongan Kavling",
    poin1: "✅  1 Menit ke Jl. Simo-Kalioso",
    poin2: "✅  3 Menit ke KUA Nogosari",
    poin3: "✅  3 Menit ke SPBU Nogosari",
    poin4: "✅  5 Menit ke Pasar Nogosari",
    poin5: "✅  5 Menit ke Polsek Nogosari",
    poin6: "✅  6 Menit ke Puskesmas Nogosari",
    poin7: "✅ 20 Menit ke Bandara Adi Soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling1,
    imageLg: Kavling1,
    country: "Boyolali",
    daerah: "Keyongan",
    address: "Keyongan, Nogosari, Boyolali",
    price: "108",
    denah: Denah,
  },
  {
    id: 10,
    type: "A2",
    name: "Ginasteel Kavling",
    poin1: "✅  1 menit ke Wisata embung giriroto",
    poin2: "✅  1 menit ke SDN 3 Giriroto",
    poin3: "✅  5 menit ke SPBU Gondangrejo",
    poin4: "✅  5 menit ke Jl Raya Solo - Purwodadi",
    poin5: "✅  5 menit ke Jalan  Raya Ngemplak-Kalioso",
    poin6: "✅  4 menit ke Taman Qris",
    poin7: "✅ 15 Asrama haji donohudan",
    poin8: "✅ 15 menit ke Gerbang Toll Ngemplak",
    poin9: "✅ 15 menit ke Gerbang Toll Gondangrejo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling2,
    imageLg: Kavling2,
    country: "Boyolali",
    daerah: "Kismoyoso",
    address: "Kismoyoso, Ngemplak, Boyolali",
    price: "78",
    denah: Denah2,
  },
  {
    id: 11,
    type: "B1",
    name: "Ginasteel Kavling",
    poin1: "✅  1 menit ke Wisata embung giriroto",
    poin2: "✅  1 menit ke SDN 3 Giriroto",
    poin3: "✅  5 menit ke SPBU Gondangrejo",
    poin4: "✅  5 menit ke Jl Raya Solo - Purwodadi",
    poin5: "✅  5 menit ke Jalan  Raya Ngemplak-Kalioso",
    poin6: "✅  4 menit ke Taman Qris",
    poin7: "✅ 15 Asrama haji donohudan",
    poin8: "✅ 15 menit ke Gerbang Toll Ngemplak",
    poin9: "✅ 15 menit ke Gerbang Toll Gondangrejo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling2,
    imageLg: Kavling2,
    country: "Boyolali",
    daerah: "Kismoyoso",
    address: "Kismoyoso, Ngemplak, Boyolali",
    price: "78",
    denah: Denah2,
  },
  {
    id: 12,
    type: "B2",
    name: "Ginasteel Kavling",
    poin1: "✅  1 menit ke Wisata embung giriroto",
    poin2: "✅  1 menit ke SDN 3 Giriroto",
    poin3: "✅  5 menit ke SPBU Gondangrejo",
    poin4: "✅  5 menit ke Jl Raya Solo - Purwodadi",
    poin5: "✅  5 menit ke Jalan  Raya Ngemplak-Kalioso",
    poin6: "✅  4 menit ke Taman Qris",
    poin7: "✅ 15 Asrama haji donohudan",
    poin8: "✅ 15 menit ke Gerbang Toll Ngemplak",
    poin9: "✅ 15 menit ke Gerbang Toll Gondangrejo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling2,
    imageLg: Kavling2,
    country: "Boyolali",
    daerah: "Kismoyoso",
    address: "Kismoyoso, Ngemplak, Boyolali",
    price: "84",
    denah: Denah2,
  },
  {
    id: 13,
    type: "B4",
    name: "Ginasteel Kavling",
    poin1: "✅  1 menit ke Wisata embung giriroto",
    poin2: "✅  1 menit ke SDN 3 Giriroto",
    poin3: "✅  5 menit ke SPBU Gondangrejo",
    poin4: "✅  5 menit ke Jl Raya Solo - Purwodadi",
    poin5: "✅  5 menit ke Jalan  Raya Ngemplak-Kalioso",
    poin6: "✅  4 menit ke Taman Qris",
    poin7: "✅ 15 Asrama haji donohudan",
    poin8: "✅ 15 menit ke Gerbang Toll Ngemplak",
    poin9: "✅ 15 menit ke Gerbang Toll Gondangrejo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling2,
    imageLg: Kavling2,
    country: "Boyolali",
    daerah: "Kismoyoso",
    address: "Kismoyoso, Ngemplak, Boyolali",
    price: "70",
    denah: Denah2,
  },
  {
    id: 14,
    type: "B5",
    name: "Ginasteel Kavling",
    poin1: "✅  1 menit ke Wisata embung giriroto",
    poin2: "✅  1 menit ke SDN 3 Giriroto",
    poin3: "✅  5 menit ke SPBU Gondangrejo",
    poin4: "✅  5 menit ke Jl Raya Solo - Purwodadi",
    poin5: "✅  5 menit ke Jalan  Raya Ngemplak-Kalioso",
    poin6: "✅  4 menit ke Taman Qris",
    poin7: "✅ 15 Asrama haji donohudan",
    poin8: "✅ 15 menit ke Gerbang Toll Ngemplak",
    poin9: "✅ 15 menit ke Gerbang Toll Gondangrejo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling2,
    imageLg: Kavling2,
    country: "Boyolali",
    daerah: "Kismoyoso",
    address: "Kismoyoso, Ngemplak, Boyolali",
    price: "70",
    denah: Denah2,
  },
  {
    id: 15,
    type: "A3",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "69",
    denah: Denah3,
  },
  {
    id: 16,
    type: "A4",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "69",
    denah: Denah3,
  },
  {
    id: 17,
    type: "A5",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "69",
    denah: Denah3,
  },
  {
    id: 18,
    type: "A6",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "56",
    denah: Denah3,
  },
  {
    id: 19,
    type: "A7",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "60",
    denah: Denah3,
  },
  {
    id: 20,
    type: "A8",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "60",
    denah: Denah3,
  },
  {
    id: 21,
    type: "A9",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "60",
    denah: Denah3,
  },
  {
    id: 22,
    type: "B3",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 23,
    type: "B4",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 24,
    type: "B5",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 25,
    type: "B6",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 26,
    type: "B7",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 27,
    type: "B8",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 28,
    type: "B9",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 29,
    type: "B10",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "57",
    denah: Denah3,
  },
  {
    id: 30,
    type: "B11",
    name: "Adem Ayem Kavling",
    poin1: "✅  1 Menit ke MI Muhammadiyah Widoro",
    poin2: "✅  1 Menit ke Lapangan Pojok",
    poin3: "✅  1 Menit ke Swalayan Abimanyu Mart",
    poin4: "✅  1 Menit ke Ponpes Salafiyah-Afdholush shofiyyah ",
    poin5: "✅  4 Menit ke SMA Negeri 1 Nogosari",
    poin6: "✅  21 Menit ke Bandara Internasional Adi soemarmo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    image: Kavling3,
    imageLg: Kavling3,
    country: "Boyolali",
    daerah: "Pojok",
    address: "Pojok, Nogosari, Boyolali",
    price: "67",
    denah: Denah3,
  },
];

export const dealDone = [
  {
    id: 1,
    img: gambar1,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
  {
    id: 2,
    img: gambar2,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
  {
    id: 3,
    img: gambar3,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
  {
    id: 4,
    img: gambar4,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
  {
    id: 5,
    img: gambar5,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
  {
    id: 6,
    img: gambar6,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
  {
    id: 7,
    img: gambar7,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
  {
    id: 8,
    img: gambar8,
    desc: "Proses penyerahan sertifikat tanah kepada pelanggan simply property",
  },
];

export const testimoni = [
  {
    id: 1,
    img: person1,
    text: "Alhamdulillah. timnya ramah, owner-nya juga ramah, dan harganya pun juga ramah",
  },
  {
    id: 2,
    img: person2,
    text: "Admin-adminnya orangnya baik, sertifikatnya juga cepet sesuai dengan schedule",
  },
  {
    id: 3,
    img: person3,
    text: "Pembayarannya mudah, bisa cash atau angsur. Angsurannya juga mudah. Timnya juga baik",
  },
  {
    id: 4,
    img: person4,
    text: "Admin-adminnya orangnya baik, sertifikatnya juga cepet sesuai dengan schedule",
  },
];
